データをtrain,valid,testに分割する

In [2]:
import pandas as pd
transactions =pd.read_csv("C:/kaggle_nvidia/kaggle_hm/competitions/hm/data/processed/transactions_converted.csv",dtype={"article_id": str})

In [7]:
articles = pd.read_csv("C:/kaggle_nvidia/kaggle_hm/competitions/hm/data/raw/articles.csv")
articles.head()

,article_id,product_code,prod_name,product_type_no,product_type_name,product_group_name,graphical_appearance_no,graphical_appearance_name,colour_group_code,colour_group_name,...,department_name,index_code,index_name,index_group_no,index_group_name,section_no,section_name,garment_group_no,garment_group_name,detail_desc
0,108775015,108775,Strap top,253,Vest top,Garment Upper body,1010016,Solid,9,Black,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
1,108775044,108775,Strap top,253,Vest top,Garment Upper body,1010016,Solid,10,White,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
2,108775051,108775,Strap top (1),253,Vest top,Garment Upper body,1010017,Stripe,11,Off White,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
3,110065001,110065,OP T-shirt (Idro),306,Bra,Underwear,1010016,Solid,9,Black,...,Clean Lingerie,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Microfibre T-shirt bra with underwired, moulde..."
4,110065002,110065,OP T-shirt (Idro),306,Bra,Underwear,1010016,Solid,10,White,...,Clean Lingerie,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Microfibre T-shirt bra with underwired, moulde..."

In [ ]:
cutomer = pd.read_csv("C:/kaggle_nvidia/kaggle_hm/competitions/hm/data/processed/articles.csv",dtype={"article_id": str})
articles.head()

In [16]:
transactions.head()

        t_dat  customer_id  article_id     price  sales_channel_id
0  2018-09-20            3  0663713001  0.050831                 2
1  2018-09-20            3  0541518023  0.030492                 2
2  2018-09-20            8  0505221004  0.015237                 2
3  2018-09-20            8  0685687003  0.016932                 2
4  2018-09-20            8  0685687004  0.016932                 2

In [17]:
# t_datをdatetime型に変換
transactions["t_dat"] = pd.to_datetime(transactions["t_dat"])
# 基準日（データの最終日）を確認
print(transactions["t_dat"].max())  # 2020-09-19が出るはず
print(transactions["t_dat"].min())  # 2018-09-20が出るはず

2020-09-22 00:00:00
2018-09-20 00:00:00

In [18]:
# 基準日を設定（データの最終日）
reference_date = transactions["t_dat"].max()

# 各トランザクションが「最終日から何週前か」を週番号として割り振る
# 最新が週番号が大きくなるように設定
transactions["week"] = (
    (transactions["t_dat"] - transactions["t_dat"].min()).dt.days // 7
)

# week列を確認
print(transactions["week"].min())
print(transactions["week"].max())
print(transactions[["t_dat", "week"]].head(10))

0
104
       t_dat  week
0 2018-09-20     0
1 2018-09-20     0
2 2018-09-20     0
3 2018-09-20     0
4 2018-09-20     0
5 2018-09-20     0
6 2018-09-20     0
7 2018-09-20     0
8 2018-09-20     0
9 2018-09-20     0

In [19]:
# valid用の設定
# x:week104より前の購買履歴
# y:week104以降の購買履歴
valid_x = transactions[transactions["week"] <104]
valid_y = transactions[transactions["week"] == 104]

print(f"valid_x: {len(valid_x)}行")
print(f"valid_y: {len(valid_y)}行")
print(f"valid_yのユニークユーザー数: {valid_y['customer_id'].nunique()}")
print(f"valid_yのユニーク商品数: {valid_y['article_id'].nunique()}")

valid_x: 31575041行
valid_y: 213283行
valid_yのユニークユーザー数: 61950
valid_yのユニーク商品数: 17265

In [20]:
# 週番号を付与したtransactionsを保存
transactions.to_csv(
    "C:/kaggle_nvidia/kaggle_hm/competitions/hm/data/processed/transactions_with_week.csv",
    index=False
)

# valid_x・valid_yを保存
valid_x.to_csv(
    "C:/kaggle_nvidia/kaggle_hm/competitions/hm/data/processed/valid_x.csv",
    index=False
)

valid_y.to_csv(
    "C:/kaggle_nvidia/kaggle_hm/competitions/hm/data/processed/valid_y.csv",
    index=False
)

print("保存完了")

保存完了